use rand::{Rng, RngExt};

use crate::keyboard::layout::Layout;

/// Configuration parameters for the simulated annealing algorithm.
///
/// The algorithm starts at `t_start` and repeatedly multiplies the temperature
/// by `alpha` until it reaches `t_min`. For each temperature level it performs
/// `iterations_per_temp` random neighbor evaluations.
/// Larger values of `iterations_per_temp` and slower cooling schedules
/// usually increase solution quality, but also increase runtime.
pub struct AnnealingConfig {
    pub t_start: f64,
    pub t_min: f64,
    pub alpha: f64,
    pub iterations_per_temp: usize,
}

impl Default for AnnealingConfig {
    fn default() -> Self {
        Self { t_start: 1.0, t_min: 1e-4, alpha: 0.9995, iterations_per_temp: 1_000 }
    }
}

/// Result produced by simulated annealing.
///
/// The result contains the `best_layout` found during the search, its cost - `best_cost`,
/// and the history of the best cost after each temperature level - `cost_history`.
pub struct AnnealingResult<const N: usize> {
    pub best_layout: Layout<N>,
    pub best_cost: f64,
    pub cost_history: Vec<f64>,
}

/// Runs simulated annealing on a keyboard layout.
///
/// The algorithm searches over permutations of `Layout<N>`. A neighbor is
/// generated by swapping two randomly selected key assignments in-place.
/// If the candidate is rejected, the swap is immediately reverted.
///
/// The algorithm itself is independent from keyboard geometry and ergonomic
/// metrics. Those details are provided through `cost_func`, which maps a
/// layout to a numeric cost. Lower cost is considered better.
///
/// The search is deterministic if the supplied random number generator is
/// deterministic and seeded.
pub fn simulated_annealing<const N: usize, Func>(
    initial: Layout<N>,
    config: &AnnealingConfig,
    rng: &mut impl Rng,
    cost_func: Func,
) -> AnnealingResult<N>
where
    Func: Fn(&Layout<N>) -> f64,
{
    let mut current_layout = initial;
    let mut current_cost = cost_func(&current_layout);

    let mut best_layout = current_layout.clone();
    let mut best_cost = current_cost;

    let mut cost_history: Vec<f64> = vec![best_cost];

    let mut temperature = config.t_start;
    if N < 2 {
        return AnnealingResult { best_layout, best_cost, cost_history };
    }

    while temperature > config.t_min {
        for _ in 0..config.iterations_per_temp {
            let first = rng.random_range(0..N);
            let mut second = rng.random_range(0..N);

            while first == second {
                second = rng.random_range(0..N);
            }
            current_layout.swap(first, second);

            let new_cost = cost_func(&current_layout);
            let delta = new_cost - current_cost;

            if delta <= 0.0 || should_accept_worse(delta, temperature, rng) {
                current_cost = new_cost;

                if new_cost < best_cost {
                    best_layout = current_layout.clone();
                    best_cost = new_cost;
                }
            } else {
                current_layout.swap(first, second); // getting back to previous layout
            }
        }
        cost_history.push(best_cost);
        temperature *= config.alpha;
    }

    AnnealingResult { best_layout, best_cost, cost_history }
}

fn should_accept_worse(delta: f64, temperature: f64, rng: &mut impl Rng) -> bool {
    let prob = (-delta / temperature).exp();
    rng.random_range(0.0..1.0) < prob
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::SmallRng;
    use rand::{RngExt, SeedableRng};

    fn test_config() -> AnnealingConfig {
        AnnealingConfig { t_start: 1.0, t_min: 1e-2, alpha: 0.9, iterations_per_temp: 10 }
    }

    fn run_sa<const N: usize, F>(
        initial: Layout<N>,
        config: &AnnealingConfig,
        seed: u64,
        cost_func: F,
    ) -> AnnealingResult<N>
    where
        F: Fn(&Layout<N>) -> f64,
    {
        let mut rng = SmallRng::seed_from_u64(seed);
        simulated_annealing(initial, config, &mut rng, cost_func)
    }

    fn us_mismatch_cost<const N: usize>(layout: &Layout<N>) -> f64 {
        let qwerty = Layout::standard_us();
        layout.mappings_iter().zip(qwerty.mappings_iter()).filter(|(a, b)| a.base != b.base).count()
            as f64
    }

    fn scramble_layout<const N: usize>(layout: &mut Layout<N>, seed: u64, swaps: usize) {
        let mut rng = SmallRng::seed_from_u64(seed);
        for _ in 0..swaps {
            let first = rng.random_range(0..N);
            let mut second = rng.random_range(0..N);
            while first == second {
                second = rng.random_range(0..N);
            }

            layout.swap(first, second);
        }
    }

    #[test]
    fn sa_best_cost_is_not_worse_than_initial_cost() {
        let mut layout = Layout::standard_us();
        scramble_layout(&mut layout, 42, 10);
        let initial_cost = us_mismatch_cost(&layout);
        let result = run_sa(layout, &test_config(), 7, us_mismatch_cost);

        assert!(
            result.best_cost <= initial_cost,
            "best_cost={} should be <= initial_cost={}",
            result.best_cost,
            initial_cost
        );
    }

    #[test]
    fn cost_history_is_non_increasing() {
        let mut layout = Layout::standard_us();
        scramble_layout(&mut layout, 42, 10);
        let result = run_sa(layout, &test_config(), 7, us_mismatch_cost);
        let is_non_increasing = result.cost_history.windows(2).all(|w| w[0] >= w[1]);

        assert!(
            is_non_increasing,
            "cost history should be non-increasing: {:?}",
            result.cost_history
        );
    }

    #[test]
    fn same_seed_gives_same_result() {
        let config = test_config();
        let result_a = run_sa(Layout::standard_us(), &config, 7, us_mismatch_cost);
        let result_b = run_sa(Layout::standard_us(), &config, 7, us_mismatch_cost);

        assert_eq!(result_a.best_cost, result_b.best_cost);
        assert_eq!(result_a.best_layout, result_b.best_layout);
        assert_eq!(result_a.cost_history, result_b.cost_history);
    }

    #[test]
    fn best_cost_matches_best_layout() {
        let mut layout = Layout::standard_us();
        scramble_layout(&mut layout, 42, 10);
        let result = run_sa(layout, &test_config(), 7, us_mismatch_cost);

        assert_eq!(result.best_cost, us_mismatch_cost(&result.best_layout));
    }

    #[test]
    fn cost_history_starts_with_initial_cost() {
        let mut layout = Layout::standard_us();
        scramble_layout(&mut layout, 42, 10);
        let initial_cost = us_mismatch_cost(&layout);
        let result = run_sa(layout, &test_config(), 7, us_mismatch_cost);

        assert_eq!(result.cost_history.first().copied(), Some(initial_cost));
    }

    #[test]
    fn cost_history_has_expected_length() {
        let config =
            AnnealingConfig { t_start: 1.0, t_min: 0.25, alpha: 0.5, iterations_per_temp: 1 };
        let result = run_sa(Layout::standard_us(), &config, 0, us_mismatch_cost);

        assert_eq!(result.cost_history.len(), 3);
    }

    #[test]
    fn improving_swap_is_kept() {
        let initial = Layout::standard_us();
        let snapshot = initial.clone();
        let config =
            AnnealingConfig { t_start: 1.0, t_min: 0.5, alpha: 0.1, iterations_per_temp: 1 };
        let cost = |layout: &Layout<_>| if *layout == snapshot { 1.0 } else { 0.0 };
        let result = run_sa(initial, &config, 123, cost);

        assert_eq!(result.best_cost, 0.0);
        assert_ne!(result.best_layout, snapshot);
    }

    #[test]
    fn should_accept_equal_cost_move() {
        let mut rng = SmallRng::seed_from_u64(0);
        assert!(should_accept_worse(0.0, 1.0, &mut rng));
    }

    #[test]
    fn should_reject_very_bad_move_at_low_temperature() {
        let mut rng = SmallRng::seed_from_u64(0);
        assert!(!should_accept_worse(1.0, 1e-9, &mut rng));
    }
}
